import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  common: {
    appName: 'Golden Hour AI',
    tagline: 'Turn panic into coordinated action.',
    call: 'Call {{number}}',
    callEmergency: 'Call emergency services',
    cancel: 'Cancel',
    continue: 'Continue',
    back: 'Back',
    save: 'Save changes',
    done: 'Done',
    yes: 'Yes',
    no: 'No',
    unknown: 'Not sure',
    loading: 'Loading…',
    retry: 'Try again',
    demoLabel: 'Demonstration only',
    protocolDisclaimer: 'Demonstration guidance requiring clinical review before production use.',
    selfReported: 'Self-reported information',
    stale: 'Saved offline · may be out of date',
  },
  nav: { home: 'Home', history: 'History', readiness: 'Readiness', settings: 'Settings', menu: 'Open menu', closeMenu: 'Close menu', profile: 'Emergency profile', signOut: 'Sign out', primary: 'Primary navigation' },
  source: { userReported: 'user reported', profile: 'profile snapshot', aiExtracted: 'AI extracted', confirmed: 'confirmed', unknown: 'unknown' },
  status: { online: 'Online', offline: 'Offline', connected: 'Live updates connected', connecting: 'Connecting to live updates', polling: 'Live updates unavailable · checking periodically' },
  landing: { eyebrow: 'Clear next steps when every second matters', title: 'Turn panic into coordinated action.', body: 'Capture what happened, coordinate family, and prepare a clear handover—without delaying a call to emergency services.', start: 'Open demo', nearby: 'Help someone nearby', create: 'Create an account', signIn: 'Sign in', safety: 'Not a doctor, diagnostic system, ambulance provider, or replacement for emergency services.', feature1: 'One calm action at a time', feature2: 'Keep family coordinated', feature3: 'Share only what you approve', safetySummary: 'Product safety summary', privacyEyebrow: 'Privacy by default', privacyTitle: 'Only share what helps right now.', privacyBody: 'Emergency links are time-bound and limited. Insurance, private documents, and home address stay hidden by default.' },
  auth: { register: 'Create your account', login: 'Welcome back', email: 'Email address', password: 'Password', name: 'Your name', confirmPassword: 'Confirm password', create: 'Create account', signIn: 'Sign in', demo: 'Use fictional demo account', invalid: 'Check your details and try again.', passwordHint: 'Use at least 12 characters with uppercase, lowercase, number, and symbol.', checking: 'Checking your secure session…', privacy: 'Authentication uses secure, HTTP-only cookies. Passwords are never stored in this browser.' },
  home: { greeting: 'Good evening{{name}}', ready: 'Emergency profile is {{score}}% ready', emergency: 'Start emergency help', emergencyHint: 'Press once, then choose who needs help. Calling {{number}} stays available.', active: 'Active emergency', resume: 'Resume coordination', quick: 'Prepare before an emergency', card: 'Emergency card', contacts: 'Contacts', sharing: 'Sharing', simpleTask: 'Current task', familyStatus: 'Family connected' },
  start: { title: 'Who needs help?', subtitle: 'Choose one. You can change this later.', self: 'Help me', family: 'Help a family member', bystander: 'Help someone nearby', category: 'What best describes it?', categoryHint: 'Choose Other if you are not sure.', confirm: 'Continue to describe what happened', useOwnerProfile: 'Use my saved profile for this patient', useOwnerProfileHint: 'Select only if the saved profile belongs to the family member who needs help. This is off by default.' },
  category: { chestPain: 'Chest pain', breathingDifficulty: 'Breathing difficulty', fallInjury: 'Fall or injury', unconscious: 'Unconscious person', seizure: 'Seizure', heavyBleeding: 'Heavy bleeding', roadAccident: 'Road accident', allergicReaction: 'Allergic reaction', childEmergency: 'Child emergency', unknown: 'Other or unknown' },
  capture: { title: 'Tell us what happened', subtitle: 'Use your own words. Names and medicine terms stay unchanged.', speak: 'Speak for up to 30 seconds', stop: 'Stop recording', typed: 'Type the situation', placeholder: 'Example: My father suddenly has chest pain and is sweating…', demo: 'Use Hindi demo', submit: 'Use this description', skipAi: 'Skip AI and use selected category', micDenied: 'Microphone permission is blocked or unavailable. You can type what happened immediately below. To record later, allow microphone access in this browser’s site permissions and try again.', location: 'Current location', useLocation: 'Use my location', manualLocation: 'Type location instead', locationDenied: 'Automatic location was not available. Keep the landmark or address above, and optionally enter a map pin below.', locationReady: 'Location coordinates are ready: {{latitude}}, {{longitude}}. They will be shared when you submit this report.', manualPin: 'Optional manual map pin', manualPinHint: 'Enter decimal coordinates from a trusted map. Your typed landmark or address remains attached to the pin.', latitude: 'Latitude (−90 to 90)', longitude: 'Longitude (−180 to 180)', pinConsent: 'I consent to share these coordinates for this active emergency.', usePin: 'Use this map pin', pinConsentRequired: 'Confirm consent before using the map pin.', pinInvalid: 'Enter a latitude from −90 to 90 and a longitude from −180 to 180.', pinReady: 'Map pin is ready and will be saved with this report.', locationSaveFailed: 'The report was saved, but the coordinates could not be saved. Your typed location is still available.' },
  questions: { title: 'Two quick checks', subtitle: 'Answer only if it is safe to check. You can choose Not sure.', count: 'Question {{current}} of {{total}}', next: 'Next question', finish: 'Show next action', conscious: 'Is the person awake and responding?', breathing: 'Is the person breathing normally?', bleeding: 'Is severe bleeding visible?', fallback: 'This question is shown in English because a reviewed translation is unavailable.', languageConfirm: 'Choose the language you want to use. Detection confidence was low.', languageLabelsOnly: 'Changing this display language does not change the stored report or interpreted facts.', reportReview: 'Review the report before confirming', originalReport: 'Original report', interpretedFacts: 'Interpreted facts — not yet confirmed', noExtractedFacts: 'No interpreted facts are available.', confirmFacts: 'Does this interpretation match what you reported?', reviseTitle: 'Interpretation not confirmed', reviseBody: 'The interpretation remains unconfirmed. Edit the original report and submit it again before continuing.', editReport: 'Edit and resubmit report' },
  action: { title: 'Do this now', step: 'Action {{current}} of {{total}}', next: 'Next action', coordinate: 'Open coordination room', uncertainty: 'Some details are uncertain', confirmFacts: 'Confirm what we understood', original: 'Original description', language: '{{language}} detected · {{confidence}}% confidence', noClaim: 'Opening the phone dialler does not confirm that a call connected.', callConnected: 'I confirm the call connected', callInitiated: 'Attempting to open your phone dialler. Call connection is not confirmed.', callConnectedTitle: 'Emergency call connected', callConnectedDetail: 'Connection confirmed by the user, not by the provider.', readAloud: 'Read approved guidance aloud', audioReady: 'Approved protocol audio is ready.', audioUnavailable: 'Approved protocol audio is unavailable. Continue using the text guidance.', translationFallback: 'A reviewed translation is unavailable, so approved protocol text is shown in English.', doNot: 'Do not', escalation: 'Escalation' },
  room: { title: 'Emergency coordination', patient: 'Emergency for {{name}}', live: 'Live situation', location: 'Location', participants: 'People connected', tasks: 'Family tasks', timeline: 'Timeline', responder: 'Responder brief', handover: 'Hospital handover', share: 'Bystander QR', close: 'Close emergency', closeConfirm: 'Close this emergency session?', closeWarning: 'This stops live coordination. It does not contact or cancel emergency services.', markDeparted: 'Patient departed', markArrived: 'Arrived at hospital', invite: 'Invite a participant', inviteName: 'Participant name', inviteRole: 'Participant role', inviteSubmit: 'Create secure invitation', inviteReady: 'Secure invitation ready', awaiting: 'Awaiting acknowledgement', acknowledged: 'Acknowledged', copyInvite: 'Copy invitation', copiedInvite: 'Invitation copied', participantEmpty: 'No participants are connected yet.', observationAdded: 'Observation added', observationSaved: 'Observation saved.', observationOffline: 'A noncritical status check was saved on this device and is waiting to sync.', departureDetail: 'Patient departure reported by a participant.', arrivalDetail: 'Hospital arrival reported by a participant.', roleOwner: 'Owner', roleFamily: 'Family', roleBystander: 'Bystander', roleCaregiver: 'Caregiver', statusActive: 'Active', statusDeparted: 'Patient departed', statusAtHospital: 'At hospital', statusClosed: 'Closed' },
  tasks: { title: 'Family task board', assign: 'Assign', accept: 'Accept', decline: 'Decline', complete: 'Mark complete', open: 'Open', accepted: 'Accepted', declined: 'Declined', completed: 'Completed', owner: 'Assigned to {{name}}', updated: 'Updated {{time}}', empty: 'No tasks yet.', critical: 'Critical' },
  brief: { responderTitle: 'Responder brief', responderIntro: 'Only emergency-relevant information approved for sharing.', handoverTitle: 'Hospital handover', handoverIntro: 'Facts are separated by source and confirmation status.', identity: 'Patient identity', observations: 'Reported observations', allergies: 'Critical allergies', conditions: 'Relevant conditions', medicines: 'Current medicines', procedure: 'Relevant procedure', contact: 'Emergency contact', confidence: 'AI interpretation confidence', uncertainty: 'Unconfirmed or unknown', timeline: 'Chronological timeline', original: 'Original description', protocol: 'Protocol version', copy: 'Copy brief', copied: 'Brief copied', conscious: 'Conscious', breathing: 'Breathing normally', bleeding: 'Severe bleeding', confirmed: 'Confirmed facts', unconfirmed: 'Unconfirmed interpretation', language: 'Languages used', languageNormalization: '{{language}} original · English normalization', noSnapshot: 'No patient profile snapshot was captured for this session.', captured: 'Profile snapshot captured {{time}}' },
  summary: { familyTab: 'Family summary', familyTitle: 'Family summary', familyIntro: 'A server-generated coordination summary using allowlisted emergency fields.', responderTitle: 'Authoritative responder summary', handoverTitle: 'Authoritative hospital handover', serverNotice: 'Generated on the server from labelled, allowlisted facts. Review before sharing.', generate: 'Generate server summary', copied: 'Server summary copied.' },
  bystander: { title: 'Emergency information', limited: 'Limited, time-bound view', call: 'Call {{number}} now', report: 'Report what you can see', conscious: 'Is the person conscious?', breathing: 'Are they breathing normally?', bleeding: 'Is there severe bleeding?', location: 'Share current location', consent: 'Share only after the person consents when possible.', contact: 'Contact family', expired: 'This emergency link is invalid, expired, or revoked.', noRecords: 'This link never shows full medical records, insurance, private documents, or home address.', anonymousIntro: 'No account is needed. Describe only what is necessary for this emergency.', submit: 'Start limited emergency session', privateToken: 'Your temporary access stays in this page and is not added to the link.' },
  join: { title: 'Join emergency coordination', intro: 'Accept this time-limited invitation to coordinate this emergency.', accept: 'Accept invitation', accepted: 'Invitation accepted for {{name}} as {{role}}.', acknowledge: 'Acknowledge and open coordination', missing: 'This participant invitation is missing, expired, or already used.', error: 'The invitation could not be accepted. Ask the session owner for a new link.' },
  profile: { title: 'Emergency profile', intro: 'This information is self-reported unless marked verified.', personal: 'Personal details', dob: 'Date of birth', blood: 'Blood group (optional)', allergies: 'Allergies', conditions: 'Medical conditions', medicines: 'Current medicines', procedures: 'Relevant procedures', hospital: 'Preferred hospital', doctor: 'Doctor contact', insurance: 'Insurance details', reviewed: 'Last reviewed', edit: 'Edit profile' },
  contacts: { title: 'Emergency contacts', intro: 'Add at least two people who can help coordinate.', add: 'Add contact', remove: 'Remove contact', verified: 'Verified', unverified: 'Not verified', phone: 'Phone number', relationship: 'Relationship', requestCode: 'Request verification code', code: 'Verification code', confirmCode: 'Confirm code', verifyFor: 'Verify {{name}}', challengeCreated: 'A verification challenge was created. Delivery has not been confirmed.', mockCode: 'Mock development code', mockNoSms: 'No SMS was sent in mock mode.', confirmed: 'Contact verified.', invalidCode: 'The verification code is invalid or expired.' },
  sharing: { title: 'Privacy and sharing', intro: 'Choose the minimum information a bystander may see during an active emergency.', identity: 'Name', age: 'Approximate age', allergies: 'Critical allergies', conditions: 'Medical conditions and relevant procedures', medicines: 'Current medicines', contact: 'Emergency contact', hidden: 'Insurance, address, and private documents stay hidden by default.', revoke: 'Revoke emergency link', expires: 'Expires {{time}}', qrAlt: 'Emergency sharing QR code' },
  onboarding: { title: 'Prepare your emergency profile', step: 'Step {{current}} of {{total}}', language: 'Language and response', details: 'About the patient', health: 'Self-reported health information', people: 'Emergency contacts', privacy: 'Emergency sharing', review: 'Review and approve', response: 'How should responses appear?', preferredLanguage: 'Preferred display language', responseMode: 'Response preference', text: 'Text', audio: 'Audio', both: 'Text and audio', allergyComplete: 'I listed my allergies or explicitly confirmed that I have none.', medicationComplete: 'I listed my current medicines or explicitly confirmed that I take none.', locationReview: 'I reviewed emergency location sharing on this device.', locationReviewHint: 'The device will still request permission before sharing location during an emergency.', contactNumber: 'Contact {{number}}', noContacts: 'No emergency contacts were entered.', shared: 'Approved to share during an active emergency', notShared: 'Not approved to share', locationReviewed: 'Reviewed; permission is still requested before sharing', locationNotReviewed: 'Not reviewed', approve: 'I confirm this information is accurate to the best of my knowledge', finish: 'Finish setup' },
  readiness: { title: 'Emergency readiness', score: '{{score}} out of 100', deterministic: 'Based only on completed preparation checks—not AI.', complete: 'Ready now', improve: 'Improve next', qr: 'Generate emergency QR' },
  history: { title: 'Emergency history', intro: 'Only sessions you are authorized to view appear here.', active: 'Active', closed: 'Closed', open: 'Open session', empty: 'No emergency sessions yet.' },
  settings: { title: 'Settings', language: 'Language', accessibility: 'Accessibility', appearance: 'Appearance', light: 'Light', dark: 'Dark', system: 'Use device setting', simple: 'Simple mode', simpleHint: 'Shows only the most important emergency controls.', offlineCard: 'Minimal offline emergency card', offlineHint: 'Opt in to save only approved critical fields on this device.', emergencyNumber: 'Emergency number', signOut: 'Sign out' },
  accessibility: { title: 'Accessibility', highContrast: 'High contrast', largeText: 'Larger text', reducedMotion: 'Reduce motion', keyboard: 'All controls support keyboard and switch access.', zoom: 'Layouts remain usable at 200% zoom.' },
  languages: { title: 'Language', current: 'Display language', note: 'English and Hindi are complete. Other listed languages currently include core emergency controls and fall back to English.' },
  offline: { title: 'You are offline', body: 'Calling {{number}} still uses your phone network. AI and live coordination need internet access.', card: 'Saved emergency card', none: 'No offline card is saved on this device.', queue: '{{count}} noncritical update waiting to sync', retry: 'Check connection', protocol: 'Cached reviewed guidance', protocolUnavailable: 'Reviewed guidance was not cached on this device. Call emergency services and reconnect when possible.', name: 'Name', age: 'Approximate age', allergies: 'Critical allergies', saved: 'Saved {{time}}', privacy: 'Free-text observations are not retained offline. Only an allowlisted noncritical status event can wait to sync.' },
  errors: { genericTitle: 'Something went wrong', genericBody: 'Your emergency-call option is still available. Reload this page or return home.', reload: 'Reload page', home: 'Return home', unauthorizedTitle: 'You cannot view this page', unauthorizedBody: 'Sign in with an account that participates in this emergency.', notFoundTitle: 'Page not found', notFoundBody: 'The link may be outdated or incomplete.' },
};

const hi: typeof en = {
  common: { appName: 'गोल्डन आवर AI', tagline: 'घबराहट को समन्वित कार्रवाई में बदलें।', call: '{{number}} पर कॉल करें', callEmergency: 'आपातकालीन सेवा को कॉल करें', cancel: 'रद्द करें', continue: 'आगे बढ़ें', back: 'पीछे', save: 'बदलाव सहेजें', done: 'हो गया', yes: 'हाँ', no: 'नहीं', unknown: 'पता नहीं', loading: 'लोड हो रहा है…', retry: 'फिर कोशिश करें', demoLabel: 'केवल प्रदर्शन', protocolDisclaimer: 'प्रदर्शन मार्गदर्शन—उत्पादन में उपयोग से पहले चिकित्सकीय समीक्षा आवश्यक है।', selfReported: 'स्वयं बताई गई जानकारी', stale: 'ऑफ़लाइन सहेजा गया · पुराना हो सकता है' },
  nav: { home: 'होम', history: 'इतिहास', readiness: 'तैयारी', settings: 'सेटिंग्स', menu: 'मेन्यू खोलें', closeMenu: 'मेन्यू बंद करें', profile: 'आपातकालीन प्रोफ़ाइल', signOut: 'साइन आउट', primary: 'मुख्य नेविगेशन' },
  source: { userReported: 'उपयोगकर्ता ने बताया', profile: 'प्रोफ़ाइल स्नैपशॉट', aiExtracted: 'AI द्वारा निकाला', confirmed: 'पुष्ट', unknown: 'अज्ञात' },
  status: { online: 'ऑनलाइन', offline: 'ऑफ़लाइन', connected: 'लाइव अपडेट जुड़े हैं', connecting: 'लाइव अपडेट जुड़ रहे हैं', polling: 'लाइव अपडेट उपलब्ध नहीं · समय-समय पर जाँच हो रही है' },
  landing: { eyebrow: 'हर सेकंड महत्वपूर्ण होने पर स्पष्ट अगला कदम', title: 'घबराहट को समन्वित कार्रवाई में बदलें।', body: 'क्या हुआ दर्ज करें, परिवार को जोड़ें और स्पष्ट अस्पताल हैंडओवर तैयार करें—आपातकालीन सेवा को कॉल करने में देरी किए बिना।', start: 'डेमो खोलें', nearby: 'पास के व्यक्ति की मदद करें', create: 'खाता बनाएँ', signIn: 'साइन इन', safety: 'यह डॉक्टर, निदान प्रणाली, एम्बुलेंस प्रदाता या आपातकालीन सेवाओं का विकल्प नहीं है।', feature1: 'एक समय में एक सरल कदम', feature2: 'परिवार को समन्वित रखें', feature3: 'केवल स्वीकृत जानकारी साझा करें', safetySummary: 'उत्पाद सुरक्षा सारांश', privacyEyebrow: 'गोपनीयता पहले', privacyTitle: 'अभी केवल उपयोगी जानकारी साझा करें।', privacyBody: 'आपात लिंक समयबद्ध और सीमित हैं। बीमा, निजी दस्तावेज़ और घर का पता डिफ़ॉल्ट रूप से छिपे रहते हैं।' },
  auth: { register: 'अपना खाता बनाएँ', login: 'वापसी पर स्वागत है', email: 'ईमेल पता', password: 'पासवर्ड', name: 'आपका नाम', confirmPassword: 'पासवर्ड की पुष्टि करें', create: 'खाता बनाएँ', signIn: 'साइन इन', demo: 'काल्पनिक डेमो खाता उपयोग करें', invalid: 'जानकारी जाँचकर फिर कोशिश करें।', passwordHint: 'कम से कम 12 अक्षर रखें, जिनमें बड़ा अक्षर, छोटा अक्षर, संख्या और चिह्न हो।', checking: 'आपका सुरक्षित सत्र जाँचा जा रहा है…', privacy: 'प्रमाणीकरण सुरक्षित HTTP-only कुकी का उपयोग करता है। पासवर्ड इस ब्राउज़र में कभी सहेजे नहीं जाते।' },
  home: { greeting: 'शुभ संध्या{{name}}', ready: 'आपातकालीन प्रोफ़ाइल {{score}}% तैयार है', emergency: 'आपातकालीन मदद शुरू करें', emergencyHint: 'एक बार दबाएँ, फिर चुनें किसे मदद चाहिए। {{number}} पर कॉल हमेशा उपलब्ध है।', active: 'सक्रिय आपातकाल', resume: 'समन्वय जारी रखें', quick: 'आपातकाल से पहले तैयारी', card: 'आपातकालीन कार्ड', contacts: 'संपर्क', sharing: 'साझाकरण', simpleTask: 'वर्तमान कार्य', familyStatus: 'परिवार जुड़ा है' },
  start: { title: 'किसे मदद चाहिए?', subtitle: 'एक चुनें। इसे बाद में बदला जा सकता है।', self: 'मेरी मदद करें', family: 'परिवार के सदस्य की मदद करें', bystander: 'पास के व्यक्ति की मदद करें', category: 'स्थिति का सबसे अच्छा वर्णन क्या है?', categoryHint: 'पता न हो तो अन्य चुनें।', confirm: 'क्या हुआ बताने के लिए आगे बढ़ें', useOwnerProfile: 'इस मरीज़ के लिए मेरी सुरक्षित प्रोफ़ाइल उपयोग करें', useOwnerProfileHint: 'केवल तभी चुनें जब सुरक्षित प्रोफ़ाइल उसी परिवार सदस्य की हो जिसे मदद चाहिए। यह डिफ़ॉल्ट रूप से बंद है।' },
  category: { chestPain: 'सीने में दर्द', breathingDifficulty: 'साँस लेने में कठिनाई', fallInjury: 'गिरना या चोट', unconscious: 'बेहोश व्यक्ति', seizure: 'दौरा', heavyBleeding: 'बहुत रक्तस्राव', roadAccident: 'सड़क दुर्घटना', allergicReaction: 'एलर्जी प्रतिक्रिया', childEmergency: 'बच्चे की आपात स्थिति', unknown: 'अन्य या अज्ञात' },
  capture: { title: 'बताएँ क्या हुआ', subtitle: 'अपने शब्दों में बताएँ। नाम और दवा के नाम नहीं बदले जाएँगे।', speak: 'अधिकतम 30 सेकंड बोलें', stop: 'रिकॉर्डिंग रोकें', typed: 'स्थिति लिखें', placeholder: 'उदाहरण: मेरे पिताजी को अचानक सीने में दर्द और पसीना आ रहा है…', demo: 'हिंदी डेमो उपयोग करें', submit: 'इस विवरण का उपयोग करें', skipAi: 'AI छोड़ें और चुनी श्रेणी उपयोग करें', micDenied: 'माइक्रोफ़ोन अनुमति अवरुद्ध है या उपलब्ध नहीं है। आप नीचे तुरंत घटना लिख सकते हैं। बाद में रिकॉर्ड करने के लिए ब्राउज़र की साइट अनुमतियों में माइक्रोफ़ोन चालू करके फिर प्रयास करें।', location: 'वर्तमान स्थान', useLocation: 'मेरा स्थान उपयोग करें', manualLocation: 'स्थान लिखें', locationDenied: 'स्वचालित स्थान उपलब्ध नहीं था। ऊपर लैंडमार्क या पता रखें और चाहें तो नीचे मानचित्र पिन दर्ज करें।', locationReady: 'स्थान निर्देशांक तैयार हैं: {{latitude}}, {{longitude}}। रिपोर्ट भेजने पर ये साझा होंगे।', manualPin: 'वैकल्पिक मैनुअल मानचित्र पिन', manualPinHint: 'विश्वसनीय मानचित्र से दशमलव निर्देशांक दर्ज करें। आपका लिखा लैंडमार्क या पता पिन के साथ रहेगा।', latitude: 'अक्षांश (−90 से 90)', longitude: 'देशांतर (−180 से 180)', pinConsent: 'मैं इस सक्रिय आपात स्थिति के लिए ये निर्देशांक साझा करने की सहमति देता/देती हूँ।', usePin: 'यह मानचित्र पिन उपयोग करें', pinConsentRequired: 'मानचित्र पिन उपयोग करने से पहले सहमति की पुष्टि करें।', pinInvalid: 'अक्षांश −90 से 90 और देशांतर −180 से 180 के बीच दर्ज करें।', pinReady: 'मानचित्र पिन तैयार है और इस रिपोर्ट के साथ सहेजा जाएगा।', locationSaveFailed: 'रिपोर्ट सहेजी गई, लेकिन निर्देशांक नहीं सहेजे जा सके। आपका लिखा स्थान अभी भी उपलब्ध है।' },
  questions: { title: 'दो छोटे सवाल', subtitle: 'सुरक्षित हो तभी जाँचें। पता नहीं चुन सकते हैं।', count: 'सवाल {{current}} / {{total}}', next: 'अगला सवाल', finish: 'अगला कदम दिखाएँ', conscious: 'क्या व्यक्ति जाग रहा है और प्रतिक्रिया दे रहा है?', breathing: 'क्या व्यक्ति सामान्य रूप से साँस ले रहा है?', bleeding: 'क्या बहुत रक्तस्राव दिखाई दे रहा है?', fallback: 'समीक्षित अनुवाद उपलब्ध नहीं है, इसलिए यह सवाल अंग्रेज़ी में दिख रहा है।', languageConfirm: 'अपनी पसंद की भाषा चुनें। भाषा पहचान का विश्वास कम था।', languageLabelsOnly: 'डिस्प्ले भाषा बदलने से सुरक्षित रिपोर्ट या निकाले गए तथ्य नहीं बदलते।', reportReview: 'पुष्टि से पहले रिपोर्ट की समीक्षा करें', originalReport: 'मूल रिपोर्ट', interpretedFacts: 'समझे गए तथ्य — अभी अपुष्ट', noExtractedFacts: 'कोई समझे गए तथ्य उपलब्ध नहीं हैं।', confirmFacts: 'क्या यह समझ आपकी रिपोर्ट से मेल खाती है?', reviseTitle: 'समझ की पुष्टि नहीं हुई', reviseBody: 'समझ अपुष्ट रहेगी। आगे बढ़ने से पहले मूल रिपोर्ट बदलकर फिर भेजें।', editReport: 'रिपोर्ट बदलें और फिर भेजें' },
  action: { title: 'अभी यह करें', step: 'कदम {{current}} / {{total}}', next: 'अगला कदम', coordinate: 'समन्वय कक्ष खोलें', uncertainty: 'कुछ जानकारी अनिश्चित है', confirmFacts: 'समझी गई बातों की पुष्टि करें', original: 'मूल विवरण', language: '{{language}} पहचानी गई · {{confidence}}% विश्वास', noClaim: 'फ़ोन डायलर खुलना कॉल जुड़ने की पुष्टि नहीं है।', callConnected: 'मैं पुष्टि करता/करती हूँ कि कॉल जुड़ गई', callInitiated: 'फ़ोन डायलर खोलने की कोशिश हो रही है। कॉल जुड़ने की पुष्टि नहीं है।', callConnectedTitle: 'आपात कॉल जुड़ी', callConnectedDetail: 'कॉल जुड़ने की पुष्टि उपयोगकर्ता ने की है, प्रदाता ने नहीं।', readAloud: 'स्वीकृत मार्गदर्शन सुनें', audioReady: 'स्वीकृत प्रोटोकॉल ऑडियो तैयार है।', audioUnavailable: 'स्वीकृत प्रोटोकॉल ऑडियो उपलब्ध नहीं है। टेक्स्ट मार्गदर्शन का उपयोग जारी रखें।', translationFallback: 'समीक्षित अनुवाद उपलब्ध नहीं है, इसलिए स्वीकृत प्रोटोकॉल अंग्रेज़ी में दिख रहा है।', doNot: 'यह न करें', escalation: 'स्थिति बिगड़ने पर' },
  room: { title: 'आपातकालीन समन्वय', patient: '{{name}} के लिए आपात स्थिति', live: 'वर्तमान स्थिति', location: 'स्थान', participants: 'जुड़े हुए लोग', tasks: 'परिवार के कार्य', timeline: 'समयरेखा', responder: 'रिस्पॉन्डर विवरण', handover: 'अस्पताल हैंडओवर', share: 'राहगीर QR', close: 'आपात स्थिति बंद करें', closeConfirm: 'यह आपात सत्र बंद करें?', closeWarning: 'इससे लाइव समन्वय रुकता है। यह आपातकालीन सेवा को संपर्क या रद्द नहीं करता।', markDeparted: 'मरीज़ रवाना हुआ', markArrived: 'अस्पताल पहुँचा', invite: 'प्रतिभागी को आमंत्रित करें', inviteName: 'प्रतिभागी का नाम', inviteRole: 'प्रतिभागी की भूमिका', inviteSubmit: 'सुरक्षित आमंत्रण बनाएँ', inviteReady: 'सुरक्षित आमंत्रण तैयार है', awaiting: 'स्वीकृति की प्रतीक्षा', acknowledged: 'स्वीकृत', copyInvite: 'आमंत्रण कॉपी करें', copiedInvite: 'आमंत्रण कॉपी हुआ', participantEmpty: 'अभी कोई प्रतिभागी जुड़ा नहीं है।', observationAdded: 'अवलोकन जोड़ा गया', observationSaved: 'अवलोकन सहेजा गया।', observationOffline: 'एक गैर-महत्वपूर्ण स्थिति जाँच इस डिवाइस पर सहेजी गई और सिंक की प्रतीक्षा में है।', departureDetail: 'एक प्रतिभागी ने मरीज़ के रवाना होने की सूचना दी।', arrivalDetail: 'एक प्रतिभागी ने अस्पताल पहुँचने की सूचना दी।', roleOwner: 'स्वामी', roleFamily: 'परिवार', roleBystander: 'राहगीर', roleCaregiver: 'देखभालकर्ता', statusActive: 'सक्रिय', statusDeparted: 'मरीज़ रवाना हुआ', statusAtHospital: 'अस्पताल में', statusClosed: 'बंद' },
  tasks: { title: 'परिवार कार्य बोर्ड', assign: 'सौंपें', accept: 'स्वीकार करें', decline: 'मना करें', complete: 'पूरा चिह्नित करें', open: 'खुला', accepted: 'स्वीकृत', declined: 'अस्वीकृत', completed: 'पूरा', owner: '{{name}} को सौंपा', updated: '{{time}} पर अपडेट', empty: 'अभी कोई कार्य नहीं।', critical: 'महत्वपूर्ण' },
  brief: { responderTitle: 'रिस्पॉन्डर विवरण', responderIntro: 'केवल साझा करने के लिए स्वीकृत आपात जानकारी।', handoverTitle: 'अस्पताल हैंडओवर', handoverIntro: 'जानकारी स्रोत और पुष्टि स्थिति के अनुसार अलग है।', identity: 'मरीज़ की पहचान', observations: 'बताई गई बातें', allergies: 'महत्वपूर्ण एलर्जी', conditions: 'संबंधित स्थितियाँ', medicines: 'वर्तमान दवाएँ', procedure: 'संबंधित प्रक्रिया', contact: 'आपात संपर्क', confidence: 'AI समझ का विश्वास', uncertainty: 'अपुष्ट या अज्ञात', timeline: 'क्रमानुसार समयरेखा', original: 'मूल विवरण', protocol: 'प्रोटोकॉल संस्करण', copy: 'विवरण कॉपी करें', copied: 'विवरण कॉपी हुआ', conscious: 'होश में', breathing: 'सामान्य साँस', bleeding: 'गंभीर रक्तस्राव', confirmed: 'पुष्ट जानकारी', unconfirmed: 'अपुष्ट समझ', language: 'उपयोग की गई भाषाएँ', languageNormalization: '{{language}} मूल · अंग्रेज़ी सामान्यीकरण', noSnapshot: 'इस सत्र के लिए मरीज़ की प्रोफ़ाइल स्नैपशॉट उपलब्ध नहीं है।', captured: 'प्रोफ़ाइल स्नैपशॉट {{time}} पर लिया गया' },
  summary: { familyTab: 'परिवार सारांश', familyTitle: 'परिवार सारांश', familyIntro: 'अनुमत आपात फ़ील्ड से बना सर्वर-जनित समन्वय सारांश।', responderTitle: 'आधिकारिक रिस्पॉन्डर सारांश', handoverTitle: 'आधिकारिक अस्पताल हैंडओवर', serverNotice: 'लेबल किए गए अनुमत तथ्यों से सर्वर पर बनाया गया। साझा करने से पहले समीक्षा करें।', generate: 'सर्वर सारांश बनाएँ', copied: 'सर्वर सारांश कॉपी हुआ।' },
  bystander: { title: 'आपात जानकारी', limited: 'सीमित, समयबद्ध दृश्य', call: 'अभी {{number}} पर कॉल करें', report: 'जो देख सकते हैं वह बताएँ', conscious: 'क्या व्यक्ति होश में है?', breathing: 'क्या सामान्य साँस ले रहा है?', bleeding: 'क्या बहुत रक्तस्राव है?', location: 'वर्तमान स्थान साझा करें', consent: 'संभव हो तो व्यक्ति की सहमति के बाद ही साझा करें।', contact: 'परिवार से संपर्क करें', expired: 'यह आपात लिंक अमान्य, समाप्त या रद्द है।', noRecords: 'इस लिंक पर पूर्ण मेडिकल रिकॉर्ड, बीमा, निजी दस्तावेज़ या घर का पता कभी नहीं दिखता।', anonymousIntro: 'खाते की जरूरत नहीं है। केवल इस आपात स्थिति के लिए जरूरी जानकारी बताएँ।', submit: 'सीमित आपात सत्र शुरू करें', privateToken: 'आपकी अस्थायी पहुँच इसी पेज में रहती है और लिंक में नहीं जोड़ी जाती।' },
  join: { title: 'आपात समन्वय में जुड़ें', intro: 'इस आपात स्थिति में समन्वय के लिए समयबद्ध आमंत्रण स्वीकार करें।', accept: 'आमंत्रण स्वीकार करें', accepted: '{{name}} के लिए {{role}} के रूप में आमंत्रण स्वीकार हुआ।', acknowledge: 'स्वीकार कर समन्वय खोलें', missing: 'यह आमंत्रण उपलब्ध नहीं, समाप्त या पहले उपयोग किया जा चुका है।', error: 'आमंत्रण स्वीकार नहीं हुआ। सत्र स्वामी से नया लिंक माँगें।' },
  profile: { title: 'आपातकालीन प्रोफ़ाइल', intro: 'सत्यापित चिह्न न हो तो यह जानकारी स्वयं बताई गई है।', personal: 'व्यक्तिगत जानकारी', dob: 'जन्म तिथि', blood: 'रक्त समूह (वैकल्पिक)', allergies: 'एलर्जी', conditions: 'चिकित्सकीय स्थितियाँ', medicines: 'वर्तमान दवाएँ', procedures: 'संबंधित प्रक्रियाएँ', hospital: 'पसंदीदा अस्पताल', doctor: 'डॉक्टर संपर्क', insurance: 'बीमा जानकारी', reviewed: 'अंतिम समीक्षा', edit: 'प्रोफ़ाइल बदलें' },
  contacts: { title: 'आपात संपर्क', intro: 'समन्वय में मदद कर सकने वाले कम से कम दो लोग जोड़ें।', add: 'संपर्क जोड़ें', remove: 'संपर्क हटाएँ', verified: 'सत्यापित', unverified: 'सत्यापित नहीं', phone: 'फ़ोन नंबर', relationship: 'संबंध', requestCode: 'सत्यापन कोड माँगें', code: 'सत्यापन कोड', confirmCode: 'कोड की पुष्टि करें', verifyFor: '{{name}} को सत्यापित करें', challengeCreated: 'सत्यापन चुनौती बनाई गई। डिलीवरी की पुष्टि नहीं हुई है।', mockCode: 'मॉक विकास कोड', mockNoSms: 'मॉक मोड में SMS नहीं भेजा गया।', confirmed: 'संपर्क सत्यापित हुआ।', invalidCode: 'सत्यापन कोड गलत है या समाप्त हो गया है।' },
  sharing: { title: 'गोपनीयता और साझाकरण', intro: 'सक्रिय आपात स्थिति में राहगीर को दिखने वाली न्यूनतम जानकारी चुनें।', identity: 'नाम', age: 'अनुमानित आयु', allergies: 'महत्वपूर्ण एलर्जी', conditions: 'चिकित्सकीय स्थितियाँ और संबंधित प्रक्रियाएँ', medicines: 'वर्तमान दवाएँ', contact: 'आपात संपर्क', hidden: 'बीमा, पता और निजी दस्तावेज़ डिफ़ॉल्ट रूप से छिपे रहते हैं।', revoke: 'आपात लिंक रद्द करें', expires: '{{time}} पर समाप्त', qrAlt: 'आपात साझाकरण QR कोड' },
  onboarding: { title: 'आपातकालीन प्रोफ़ाइल तैयार करें', step: 'कदम {{current}} / {{total}}', language: 'भाषा और उत्तर', details: 'मरीज़ के बारे में', health: 'स्वयं बताई स्वास्थ्य जानकारी', people: 'आपात संपर्क', privacy: 'आपात साझाकरण', review: 'समीक्षा और स्वीकृति', response: 'उत्तर कैसे दिखें?', preferredLanguage: 'पसंदीदा प्रदर्शन भाषा', responseMode: 'उत्तर की पसंद', text: 'टेक्स्ट', audio: 'ऑडियो', both: 'टेक्स्ट और ऑडियो', allergyComplete: 'मैंने अपनी एलर्जी लिखी हैं या स्पष्ट किया है कि कोई एलर्जी नहीं है।', medicationComplete: 'मैंने अपनी वर्तमान दवाएँ लिखी हैं या स्पष्ट किया है कि कोई दवा नहीं लेता/लेती।', locationReview: 'मैंने इस डिवाइस पर आपात स्थान साझाकरण की समीक्षा की है।', locationReviewHint: 'आपात स्थिति में स्थान साझा करने से पहले डिवाइस फिर भी अनुमति माँगेगा।', contactNumber: 'संपर्क {{number}}', noContacts: 'कोई आपात संपर्क दर्ज नहीं किया गया।', shared: 'सक्रिय आपात स्थिति में साझा करने की स्वीकृति', notShared: 'साझा करने की स्वीकृति नहीं', locationReviewed: 'समीक्षा की गई; साझा करने से पहले अनुमति फिर भी माँगी जाएगी', locationNotReviewed: 'समीक्षा नहीं की गई', approve: 'मेरी जानकारी के अनुसार यह सही है', finish: 'सेटअप पूरा करें' },
  readiness: { title: 'आपात तैयारी', score: '100 में {{score}}', deterministic: 'केवल पूरी की गई तैयारी जाँच पर आधारित—AI पर नहीं।', complete: 'अभी तैयार', improve: 'अगला सुधार', qr: 'आपात QR बनाएँ' },
  history: { title: 'आपात इतिहास', intro: 'केवल अधिकृत सत्र यहाँ दिखाई देते हैं।', active: 'सक्रिय', closed: 'बंद', open: 'सत्र खोलें', empty: 'अभी कोई आपात सत्र नहीं।' },
  settings: { title: 'सेटिंग्स', language: 'भाषा', accessibility: 'सुगम्यता', appearance: 'रूप', light: 'हल्का', dark: 'गहरा', system: 'डिवाइस सेटिंग', simple: 'सरल मोड', simpleHint: 'केवल सबसे महत्वपूर्ण आपात नियंत्रण दिखाता है।', offlineCard: 'न्यूनतम ऑफ़लाइन आपात कार्ड', offlineHint: 'इस डिवाइस पर केवल स्वीकृत महत्वपूर्ण जानकारी सहेजें।', emergencyNumber: 'आपात नंबर', signOut: 'साइन आउट' },
  accessibility: { title: 'सुगम्यता', highContrast: 'अधिक कंट्रास्ट', largeText: 'बड़ा टेक्स्ट', reducedMotion: 'कम गति', keyboard: 'सभी नियंत्रण कीबोर्ड और स्विच से चलते हैं।', zoom: 'लेआउट 200% ज़ूम पर भी उपयोगी है।' },
  languages: { title: 'भाषा', current: 'दिखाने की भाषा', note: 'अंग्रेज़ी और हिंदी पूर्ण हैं। अन्य भाषाओं में मुख्य आपात नियंत्रण हैं और बाकी अंग्रेज़ी में दिखते हैं।' },
  offline: { title: 'आप ऑफ़लाइन हैं', body: '{{number}} पर कॉल फ़ोन नेटवर्क से होती है। AI और लाइव समन्वय के लिए इंटरनेट चाहिए।', card: 'सहेजा आपात कार्ड', none: 'इस डिवाइस पर ऑफ़लाइन कार्ड नहीं है।', queue: '{{count}} गैर-महत्वपूर्ण अपडेट सिंक होने बाकी', retry: 'कनेक्शन जाँचें', protocol: 'कैश किया समीक्षा-युक्त मार्गदर्शन', protocolUnavailable: 'इस डिवाइस पर समीक्षित मार्गदर्शन कैश नहीं हुआ। आपात सेवा को कॉल करें और संभव होने पर फिर कनेक्ट करें।', name: 'नाम', age: 'अनुमानित आयु', allergies: 'महत्वपूर्ण एलर्जी', saved: '{{time}} पर सहेजा', privacy: 'ऑफ़लाइन मुक्त-टेक्स्ट टिप्पणी नहीं रखी जाती। केवल स्वीकृत गैर-महत्वपूर्ण स्थिति इवेंट सिंक की प्रतीक्षा कर सकता है।' },
  errors: { genericTitle: 'कुछ गड़बड़ हुई', genericBody: 'आपात कॉल विकल्प अभी भी उपलब्ध है। पेज फिर लोड करें या होम जाएँ।', reload: 'पेज फिर लोड करें', home: 'होम जाएँ', unauthorizedTitle: 'आप यह पेज नहीं देख सकते', unauthorizedBody: 'इस आपात स्थिति में शामिल खाते से साइन इन करें।', notFoundTitle: 'पेज नहीं मिला', notFoundBody: 'लिंक पुराना या अधूरा हो सकता है।' },
};

const emergencyResources = {
  mr: { title: 'आपत्कालीन मदत', start: 'आपत्कालीन मदत सुरू करा', call: '{{number}} वर कॉल करा', yes: 'होय', no: 'नाही' },
  ta: { title: 'அவசர உதவி', start: 'அவசர உதவியைத் தொடங்கு', call: '{{number}} ஐ அழைக்கவும்', yes: 'ஆம்', no: 'இல்லை' },
  te: { title: 'అత్యవసర సహాయం', start: 'అత్యవసర సహాయం ప్రారంభించండి', call: '{{number}}కు కాల్ చేయండి', yes: 'అవును', no: 'కాదు' },
  kn: { title: 'ತುರ್ತು ಸಹಾಯ', start: 'ತುರ್ತು ಸಹಾಯ ಪ್ರಾರಂಭಿಸಿ', call: '{{number}} ಗೆ ಕರೆ ಮಾಡಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ' },
  bn: { title: 'জরুরি সহায়তা', start: 'জরুরি সহায়তা শুরু করুন', call: '{{number}} নম্বরে কল করুন', yes: 'হ্যাঁ', no: 'না' },
  gu: { title: 'કટોકટી સહાય', start: 'કટોકટી સહાય શરૂ કરો', call: '{{number}} પર કૉલ કરો', yes: 'હા', no: 'ના' },
  pa: { title: 'ਐਮਰਜੈਂਸੀ ਮਦਦ', start: 'ਐਮਰਜੈਂਸੀ ਮਦਦ ਸ਼ੁਰੂ ਕਰੋ', call: '{{number}} ਉੱਤੇ ਕਾਲ ਕਰੋ', yes: 'ਹਾਂ', no: 'ਨਹੀਂ' },
  ur: { title: 'ہنگامی مدد', start: 'ہنگامی مدد شروع کریں', call: '{{number}} پر کال کریں', yes: 'ہاں', no: 'نہیں' },
};

const resources: Record<string, { translation: typeof en | Record<string, unknown> }> = {
  en: { translation: en },
  hi: { translation: hi },
};

for (const [code, emergency] of Object.entries(emergencyResources)) {
  resources[code] = {
    translation: {
      common: { call: emergency.call, yes: emergency.yes, no: emergency.no },
      home: { emergency: emergency.start },
      start: { title: emergency.title },
    },
  };
}

export const supportedLanguages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'mr', label: 'मराठी' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'ur', label: 'اردو' },
] as const;

const storedLanguage = typeof window === 'undefined' ? 'en' : window.localStorage.getItem('gh-language') ?? 'en';

void i18n.use(initReactI18next).init({
  resources,
  lng: storedLanguage,
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
  returnNull: false,
});

export function applyDocumentLanguage(language: string): void {
  if (typeof document === 'undefined') return;
  document.documentElement.lang = language;
  document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
}

applyDocumentLanguage(storedLanguage);

export default i18n;
